# Generated by Django 2.2.6 on 2024-06-22 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20240530_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=500)),
                ('Other_name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('test_result', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=400)),
                ('test_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(default='T.png', upload_to='profile_pic')),
                ('category_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.CatLeve')),
                ('doctor_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratories', to='user.Doctors')),
                ('patient_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratories', to='user.patients')),
            ],
        ),
    ]
