# Generated by Django 2.2.6 on 2024-06-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_laboratory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='category_level',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='doctor_key',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='patient_key',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='test_date',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='test_result',
        ),
    ]
