# Generated by Django 2.2.6 on 2024-06-23 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20240623_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='lab_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('test_name', models.CharField(blank=True, max_length=500, null=True)),
                ('test_result', models.FileField(blank=True, null=True, upload_to='profile_pic')),
                ('doctor_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratories', to='user.Doctors')),
                ('patient_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratories', to='user.patients')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
