# Generated by Django 2.2.6 on 2024-06-24 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_lab_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_test',
            name='doctor_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laboratories', to='user.Doctors'),
        ),
        migrations.AlterField(
            model_name='lab_test',
            name='patient_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laboratories', to='user.patients'),
        ),
    ]
